version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: telegram-status-bot
    environment:
      - BOT_TOKEN=
      - CHAT_ID=
    volumes:
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
    devices:
      - "/dev/vchiq:/dev/vchiq"
    privileged: true
    restart: unless-stopped
    command: >
      sh -c "python bot.py & while true; do python alert_bot.py; sleep 300; done"
