version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: telegram-status-bot
    pid: "host"
    env_file:
      - .env
    volumes:
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - "/dev/vchiq:/dev/vchiq"
    privileged: true
    command: >
      sh -c "python bot.py & while true; do python alert_bot.py; sleep 300; done"
    restart: unless-stopped
